name = "a99e"
default_targets = ["win32", "win64", "appimage", "macos"]
build_directory = "makelove-build"
icon_file = "graphics/icon.png"
love_version = "11.4"

love_files = [
    "::git-ls-tree::",
    "-*/.*",
]
