name: Compile
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        path: main
        submodules: true
      name: Checkout Repository
    - name: Update Packages
      run: sudo apt-get update
    - name: Install Dependencies
      run: sudo apt-get install --assume-yes wine-stable wine64 python3-pip
    - name: Install makelove
      run:
        pip3 install git+https://github.com/pfirsich/makelove/
    - name: Build
      run: cd main && python3 -m makelove
    - name: Artifact (LÖVE)
      uses: actions/upload-artifact@v2
      with:
        name: a99e-source
        path: main/makelove-build/love/${{ env.ARTIFACT_NAME_LOVE }}
    - name: Artifact (AppImage)
      uses: actions/upload-artifact@v2
      with:
        name: a99e-linux
        path: main/makelove-build/appimage/${{ env.ARTIFACT_NAME_APPIMAGE }}
    - name: Artifact (Win64)
      uses: actions/upload-artifact@v2
      with:
        name: a99e-win64
        path: main/makelove-build/win64/${{ env.ARTIFACT_NAME_WIN64 }}
    - name: Artifact (Win32)
      uses: actions/upload-artifact@v2
      with:
        name: a99e-win32
        path: main/makelove-build/win32/${{ env.ARTIFACT_NAME_WIN32 }}
    - name: Artifact (MacOS)
      uses: actions/upload-artifact@v2
      with:
        name: a99e-macos
        path: main/makelove-build/macos/${{ env.ARTIFACT_NAME_MACOS }}
